name: Debug Server Connection

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Debug SSH connection
        run: |
          echo "Testing SSH port..."
          nc -zv $SSH_SERVER $SSH_PORT || echo "Port $SSH_PORT is not accessible"
          echo "SSH port is accessible."

      - name: Test SSH connection
        run: |
          ssh -T root@37.235.102.5 "echo 'Connection successful'"

      - name: Add server key to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "37.235.102.5 ${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify known_hosts
        run: cat ~/.ssh/known_hosts
