name: Debug Server Connection

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Test server connection
        run: |
          echo "Pinging server..."
          ping -c 4 37.235.102.5 || echo "Ping failed"
          echo "Testing SSH port..."
          nc -zv 37.235.102.5 22 || echo "Port 22 is not accessible"
