name: Debug Server Connection

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Debug SSH connection
        run: |
          echo "Testing SSH port..."
          nc -zv $SSH_SERVER $SSH_PORT || echo "Port $SSH_PORT is not accessible"
          echo "SSH port is accessible."

      - name: Debug SSH keyscan
        run: |
          echo "Adding host to known_hosts..."
          ssh-keyscan -t rsa $SSH_SERVER || echo "ssh-keyscan failed"
          cat ~/.ssh/known_hosts
