name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      SSH_SERVER: 37.235.102.5
      SSH_USER: root
      SSH_PORT: 22
      WP_CLI: wp --allow-root
      PLUGIN_VERSION: ${{ github.ref_name }}
      SSH_PATH_1: /www/hosting/sokct.cz/www
      SSH_PATH_2: /www/hosting/posazavskastezka.cz/www

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Composer cache
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies with Composer
        uses: php-actions/composer@v6
        with:
          php_extensions: json
          version: 2
          dev: no

      - name: Configure Composer for Scoper
        run: |
          composer global config --no-plugins allow-plugins.wpify/scoper true
          composer global require wpify/scoper
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE/vendor
          composer install --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Add private SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add -D || true
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -t rsa -p $SSH_PORT $SSH_SERVER >> ~/.ssh/known_hosts || true
          chmod 644 ~/.ssh/known_hosts
        shell: bash

      - name: Replace plugin version
        run: |
          sed -i "s/KCT_VERSION/${{ env.PLUGIN_VERSION }}/g" kct.php
          sed -i "s/KCT_VERSION/${{ env.PLUGIN_VERSION }}/g" themes/kct/style.css

      - name: Deploy to sokct.cz
        run: |
          rsync -av --delete \
            --exclude="/.*" \
            --exclude="*.scss" \
            --exclude="*.sh" \
            --exclude="node_modules" \
            --exclude="tests" \
            . root@$SSH_SERVER:$SSH_PATH_1/wp-content/plugins/kct/

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@$SSH_SERVER <<EOF
          set -euxo pipefail
          chown -R www-data:www-data $SSH_PATH_1/wp-content/plugins/kct/
          find $SSH_PATH_1/wp-content/plugins/kct/ -type d -exec chmod 755 {} \;
          find $SSH_PATH_1/wp-content/plugins/kct/ -type f -exec chmod 644 {} \;

          cd $SSH_PATH_1
          $WP_CLI core update-db
          $WP_CLI language core update
          $WP_CLI language plugin update --all
          $WP_CLI language theme update --all
          $WP_CLI rewrite flush
          $WP_CLI cache flush
          EOF

      - name: Deploy to posazavskastezka.cz
        run: |
          rsync -av --delete \
            --exclude="/.*" \
            --exclude="*.scss" \
            --exclude="*.sh" \
            --exclude="node_modules" \
            --exclude="tests" \
            . root@$SSH_SERVER:$SSH_PATH_2/wp-content/plugins/kct/

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@$SSH_SERVER <<EOF
          set -euxo pipefail
          chown -R www-data:www-data $SSH_PATH_2/wp-content/plugins/kct/
          find $SSH_PATH_2/wp-content/plugins/kct/ -type d -exec chmod 755 {} \;
          find $SSH_PATH_2/wp-content/plugins/kct/ -type f -exec chmod 644 {} \;

          cd $SSH_PATH_2
          $WP_CLI core update-db
          $WP_CLI language core update
          $WP_CLI language plugin update --all
          $WP_CLI language theme update --all
          $WP_CLI rewrite flush
          $WP_CLI cache flush
          EOF
